"""baseline_schema

Revision ID: 0e132d0c667b
Revises: 
Create Date: 2026-06-03 14:22:05.190680

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0e132d0c667b'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_consents_status'), 'consents', ['status'], unique=False)
    op.create_index(op.f('ix_traveller_documents_document_type'), 'traveller_documents', ['document_type'], unique=False)
    op.create_index(op.f('ix_travellers_email'), 'travellers', ['email'], unique=False)
    op.create_index(op.f('ix_travellers_participation_status'), 'travellers', ['participation_status'], unique=False)
    op.create_index(op.f('ix_travellers_phone'), 'travellers', ['phone'], unique=False)
    op.alter_column('trips', 'origin_city',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=True)
    op.alter_column('trips', 'origin_state',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=True)
    op.alter_column('trips', 'status',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=False,
               existing_server_default=sa.text("'DRAFT'"))
    op.create_index(op.f('ix_trips_status'), 'trips', ['status'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_trips_status'), table_name='trips')
    op.alter_column('trips', 'status',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=False,
               existing_server_default=sa.text("'DRAFT'"))
    op.alter_column('trips', 'origin_state',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.alter_column('trips', 'origin_city',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.drop_index(op.f('ix_travellers_phone'), table_name='travellers')
    op.drop_index(op.f('ix_travellers_participation_status'), table_name='travellers')
    op.drop_index(op.f('ix_travellers_email'), table_name='travellers')
    op.drop_index(op.f('ix_traveller_documents_document_type'), table_name='traveller_documents')
    op.drop_index(op.f('ix_consents_status'), table_name='consents')
    # ### end Alembic commands ###
